### ISSUE TITLE
Crear tabla talonario en BD

### ISSUE THREAD

**Issue by danielmoret** [danielmoret/riffast-app#14]

**Comment by danielmoret** [comment]
![Image](https://user-images.githubusercontent.com/110257534/203174607-4a4da8d1-647b-49bb-ae72-cf5787871560.png)

**Comment by estefaniggt** [comment]
Listo, realice la tabla talonario en Models.py el número de mi commit es 3acce5071992c28896ff3dd041cac4ba88233ad0.
